external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/SuperTRUMP_Quote__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote</label>
    <nameField>
        <displayFormat>PQ-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Balloon__c.field-meta.xml
<CustomField>
    <fullName>Balloon__c</fullName>
    <label>Balloon</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Commencement__c.field-meta.xml
<CustomField>
    <fullName>Commencement__c</fullName>
    <label>Commencement</label>
    <type>Date</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Finance_Type__c.field-meta.xml
<CustomField>
    <fullName>Finance_Type__c</fullName>
    <label>Finance Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/IRR_NPT__c.field-meta.xml
<CustomField>
    <fullName>IRR_NPT__c</fullName>
    <label>IRR NPT</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Lending_Rate__c.field-meta.xml
<CustomField>
    <fullName>Lending_Rate__c</fullName>
    <label>Lending Rate</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Lessor_FAS__c.field-meta.xml
<CustomField>
    <fullName>Lessor_FAS__c</fullName>
    <label>Lessor FAS</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/MISF_NAT__c.field-meta.xml
<CustomField>
    <fullName>MISF_NAT__c</fullName>
    <label>MISF NAT</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Payment_Timing__c.field-meta.xml
<CustomField>
    <fullName>Payment_Timing__c</fullName>
    <label>Payment Timing</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Periodicity__c.field-meta.xml
<CustomField>
    <fullName>Periodicity__c</fullName>
    <label>Periodicity</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_Name__c</fullName>
    <label>Quote Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Quoted</fullName>
                <default>true</default>
                <label>Not Quoted</label>
            </value>
            <value>
                <fullName>Waited for Credit Check</fullName>
            </value>
            <value>
                <fullName>Ready to Quote</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Waiting for Documentation</fullName>
            </value>
            <value>
                <fullName>Ready to Book</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Rejected by Client</fullName>
            </value>
            <value>
                <fullName>Rejected by Lessor</fullName>
            </value>
            <value>
                <fullName>Rejected by Lender</fullName>
            </value>
            <value>
                <fullName>Rejected by Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Rent_IBR__c.field-meta.xml
<CustomField>
    <fullName>Rent_IBR__c</fullName>
    <label>Rent IBR</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Residual__c.field-meta.xml
<CustomField>
    <fullName>Residual__c</fullName>
    <label>Residual</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Takedown__c.field-meta.xml
<CustomField>
    <fullName>Takedown__c</fullName>
    <label>Takedown</label>
    <type>Date</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote__c/fields/Total_Lending__c.field-meta.xml
<CustomField>
    <fullName>Total_Lending__c</fullName>
    <label>Total Lending</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/SuperTRUMP_Quote_Asset__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote Asset</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quote Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <type>Date</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SuperTRUMP_Quote__c</referenceTo>
    <relationshipLabel>SuperTRUMP Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/fields/Residual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Residual_Amount__c</fullName>
    <label>Residual Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Asset__c/fields/Residual_Percent__c.field-meta.xml
<CustomField>
    <fullName>Residual_Percent__c</fullName>
    <label>Residual Percent</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Expense_Fee__c/SuperTRUMP_Quote_Expense_Fee__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote Expense Fee</label>
    <nameField>
        <displayFormat>EF-{00000}</displayFormat>
        <label>Expense Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quote Expense Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Expense_Fee__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Expense_Fee__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SuperTRUMP_Quote__c</referenceTo>
    <relationshipLabel>SuperTRUMP Expense Fees</relationshipLabel>
    <relationshipName>Expense_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Income_Fee__c/SuperTRUMP_Quote_Income_Fee__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote Income Fee</label>
    <nameField>
        <displayFormat>IF-{00000}</displayFormat>
        <label>Income Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quote Income Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Income_Fee__c/fields/Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Paid_Date__c</fullName>
    <label>Paid Date</label>
    <type>Date</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Income_Fee__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SuperTRUMP_Quote__c</referenceTo>
    <relationshipLabel>SuperTRUMP Income Fees</relationshipLabel>
    <relationshipName>Income_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Loan__c/SuperTRUMP_Quote_Loan__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote Loan</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quote Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Loan__c/fields/Number_Of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Payments__c</fullName>
    <label>Number Of Payments</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Loan__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SuperTRUMP_Quote__c</referenceTo>
    <relationshipLabel>SuperTRUMP Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Loan__c/fields/Total_Funding__c.field-meta.xml
<CustomField>
    <fullName>Total_Funding__c</fullName>
    <label>Total Funding</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Rent__c/SuperTRUMP_Quote_Rent__c.object-meta.xml
<CustomObject>
    <label>SuperTRUMP Quote Rent</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Rent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuperTRUMP Quote Rents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Rent__c/fields/Advance_Payment__c.field-meta.xml
<CustomField>
    <fullName>Advance_Payment__c</fullName>
    <label>Advance Payment</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Rent__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SuperTRUMP_Quote__c</referenceTo>
    <relationshipLabel>SuperTRUMP Rents</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

external-quote/force-app/main/default/objects/SuperTRUMP_Quote_Rent__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <label>Total Payments</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

external-quote/force-app/main/default/classes/SuperTRUMPInstaller.cls
public with sharing class SuperTRUMPInstaller {
    
    public static void installObjectRelationships(){
        List<IST__SuperTRUMP_Object_Relationships__c> toInsert = new List<IST__SuperTRUMP_Object_Relationships__c>();
        List<Map<String, String>> relationships = new List<Map<String, String>>{
            new Map<String, String>{
                'name' => 'SuperTRUMP_Quote__c',
                'childToMasterFieldName' => 'Quote__c',
                'childToMasterRelationshipName' => 'Quote__r'
            }
        };

        for (Map<String, String> entry: relationships){
            String name = entry.get('name');
            String childToMasterFieldName = entry.get('childToMasterFieldName');
            String childToMasterRelationshipName = entry.get('childToMasterRelationshipName');
            IST__SuperTRUMP_Object_Relationships__c objRel = new IST__SuperTRUMP_Object_Relationships__c();
            objRel.Name = name;
            objRel.IST__Child_To_Master_Field_Name__c = childToMasterFieldName; 
            objRel.IST__Child_To_Master_Relationship_Name__c = childToMasterRelationshipName;
            toInsert.add(objRel);
        }

        List<IST__SuperTRUMP_Object_Relationships__c> storedRelationships = [SELECT
                Name,
                IST__Child_To_Master_Field_Name__c,
                IST__Child_To_Master_Relationship_Name__c
            FROM IST__SuperTRUMP_Object_Relationships__c
            LIMIT 10000];
        
        Integer idx = 0;
        while (idx < toInsert.size()){
            IST__SuperTRUMP_Object_Relationships__c relationship = toInsert[idx];
            Boolean isFound = false;
            for (Integer sIdx = 0; sIdx < storedRelationships.size(); ++sIdx){
                IST__SuperTRUMP_Object_Relationships__c m = storedRelationships[sIdx];
                if (m.Name == relationship.Name
                    && m.IST__Child_To_Master_Field_Name__c == relationship.IST__Child_To_Master_Field_Name__c
                    && m.IST__Child_To_Master_Relationship_Name__c == relationship.IST__Child_To_Master_Relationship_Name__c
                ){
                    toInsert.remove(idx);
                    storedRelationships.remove(sIdx);
                    isFound = true;
                    break;
                }
            }
            if (!isFound){
                System.debug('Object Relationship for ' + relationship.Name + '.' + relationship.IST__Child_To_Master_Field_Name__c + '(' + relationship.IST__Child_To_Master_Relationship_Name__c + ') was NOT found.');
                ++idx;
            }
        }

        if (toInsert.size() > 0){
            System.debug(toInsert.size() + ' new object relationships being created.');
            if (!Schema.sObjectType.IST__SuperTRUMP_Object_Relationships__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Object_Relationships__c.fields.Name.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Object_Relationships__c.fields.IST__Child_To_Master_Field_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Object_Relationships__c.fields.IST__Child_To_Master_Relationship_Name__c.isCreateable())
            {
                throw new MappingException('You do not have permission to create an object of type IST__SuperTRUMP_Object_Relationships__c.');
            }
            Database.insert(toInsert, true);
        }
    }
    
    public static void installMappings(){
        List<IST__SuperTRUMP_Mapping__c> toInsert = new List<IST__SuperTRUMP_Mapping__c>();

        toInsert.add(
            new IST__SuperTRUMP_Mapping__c(
                IST__Allow_Salesforce_Changes__c = false,
                IST__External_Binding__c = 'supertrump_pricing_quote__c__quotestatus__c',
                IST__IsSynch__c = false,
                IST__IsSynch_In__c = false,
                IST__SF_Field_Name__c = 'Quote_Status__c',
                IST__SF_Master_Object_Name__c = 'SuperTRUMP_Quote__c',
                IST__SF_Object_Level__c = '1',
                IST__SF_Object_Name__c = 'SuperTRUMP_Quote__c',
                IST__SOR__c = 'SF',
                IST__ST_Field_Name__c = 'Opportunity.Quotes.Quote[].Transaction.QuoteStatus',
                IST__ST_Update_Priority__c = 0
            )
        );

        Map<String, String> quoteSyncMappings = new Map<String, String>{
            'Name' => 'Opportunity.Quotes.Quote[].Transaction.ZephyrData.Quote.CompositeQuoteNumber'
        };

        for (String fieldName : quoteSyncMappings.keySet()){
            String objName = 'SuperTRUMP_Quote__c';
            String calcField = quoteSyncMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = false,
                    IST__IsSynch_In__c = true,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Master_Object_Name__c = objName,
                    IST__SF_Object_Level__c = '1',
                    IST__SF_Object_Name__c = objName,
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }
        
        Map<String, String> quoteMappings = new Map<String, String>{
            'Cost__c' => 'Opportunity.Quotes.Quote[].Transaction.AssetCost',
            'Quote_Name__c' => 'Opportunity.Quotes.Quote[].Transaction.TransactionDescription',
            'Commencement__c' => 'Opportunity.Quotes.Quote[].Transaction.CommencementDate',
            'Finance_Type__c' => 'Opportunity.Quotes.Quote[].Transaction.ZephyrData.FinanceType',
            'Term__c' => 'Opportunity.Quotes.Quote[].Transaction.TermInMonths',
            'Payment__c' => 'Opportunity.Quotes.Quote[].Transaction.AveragePayment',
            'Payment_Timing__c' => 'Opportunity.Quotes.Quote[].Transaction.ZephyrData.PaymentTiming',
            'Periodicity__c' => 'Opportunity.Quotes.Quote[].Transaction.Periodicity',
            'Delivery_Date__c' => 'Opportunity.Quotes.Quote[].Transaction.TransactionStartDate',
            'Residual__c' => 'Opportunity.Quotes.Quote[].Transaction.ResidualAmount',
            'Total_Lending__c' => 'Opportunity.Quotes.Quote[].Transaction.TotalLendingLoans',
            'Takedown__c' => 'Opportunity.Quotes.Quote[].Transaction.TransactionStartDate',
            'Lending_Rate__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingRate',
            'Balloon__c' => 'Opportunity.Quotes.Quote[].Transaction.Balloon',
            'Mode__c' => 'Opportunity.Quotes.Quote[].Transaction.Mode',
            'Lessor_FAS__c' => 'Opportunity.Quotes.Quote[].Transaction.Results.LessorAccountingMethod',
            'IRR_NPT__c' => 'Opportunity.Quotes.Quote[].Transaction.Yields.Yield[name=IRR PTCF (per)].NPT',
            'MISF_NAT__c' => 'Opportunity.Quotes.Quote[].Transaction.Yields.Yield[name=MISF (per)].NAT',
            'Rent_IBR__c' => 'Opportunity.Quotes.Quote[].Transaction.PVs.PV[name=Rent].ValuePercent'
        };

        for (String fieldName : quoteMappings.keySet()){
            String objName = 'SuperTRUMP_Quote__c';
            String calcField = quoteMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Master_Object_Name__c = objName,
                    IST__SF_Object_Level__c = '1',
                    IST__SF_Object_Name__c = objName,
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }

        Map<String, String> assetMappings = new Map<String, String>{
            'Description__c' => 'Opportunity.Quotes.Quote[].Transaction.Assets.Asset[].Description',
            'Cost__c' => 'Opportunity.Quotes.Quote[].Transaction.Assets.Asset[].Cost',
            'Delivery__c' => 'Opportunity.Quotes.Quote[].Transaction.Assets.Asset[].DeliveryDate',
            'Residual_Amount__c' => 'Opportunity.Quotes.Quote[].Transaction.Assets.Asset[].Residual',
            'Residual_Percent__c' => 'Opportunity.Quotes.Quote[].Transaction.Assets.Asset[].ResidualAsPercentOfCost'
        };

        for (String fieldName : assetMappings.keySet()){
            String objName = 'SuperTRUMP_Quote_Asset__c';
            String parentObjName = 'SuperTRUMP_Quote__c';
            String calcField = assetMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Object_Name__c = objName,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Parent_Name__c = parentObjName,
                    IST__SF_Master_Object_Name__c = parentObjName,
                    IST__SF_Object_Level__c = '2',
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }

        Map<String, String> rentMappings = new Map<String, String>{
            'Description__c' => 'Opportunity.Quotes.Quote[].Transaction.Rents.Rent[].Description',
            'Advance_Payment__c' => 'Opportunity.Quotes.Quote[].Transaction.Rents.Rent[].AdvancePayment',
            'Total_Payments__c' => 'Opportunity.Quotes.Quote[].Transaction.Rents.Rent[].SumOfPayments',
            'Number_Of_Payments__c' => 'Opportunity.Quotes.Quote[].Transaction.Rents.Rent[].NumberOfPayments'
        };

        for (String fieldName : rentMappings.keySet()){
            String objName = 'SuperTRUMP_Quote_Rent__c';
            String parentObjName = 'SuperTRUMP_Quote__c';
            String calcField = rentMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Object_Name__c = objName,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Parent_Name__c = parentObjName,
                    IST__SF_Master_Object_Name__c = parentObjName,
                    IST__SF_Object_Level__c = '2',
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }

        Map<String, String> loanMappings = new Map<String, String>{
            'Description__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].Description',
            'Start_Date__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].FirstStartAccrual',
            'Advance_Payment__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].AdvancePayment',
            'Total_Payments__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].SumOfPayments',
            'Total_Funding__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].SumOfFundings',
            'Number_Of_Payments__c' => 'Opportunity.Quotes.Quote[].Transaction.LendingLoans.LendingLoan[].NumberOfPayments'
        };

        for (String fieldName : loanMappings.keySet()){
            String objName = 'SuperTRUMP_Quote_Loan__c';
            String parentObjName = 'SuperTRUMP_Quote__c';
            String calcField = loanMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Object_Name__c = objName,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Parent_Name__c = parentObjName,
                    IST__SF_Master_Object_Name__c = parentObjName,
                    IST__SF_Object_Level__c = '2',
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }

        Map<String, String> incomeFeeMappings = new Map<String, String>{
            'Description__c' => 'Opportunity.Quotes.Quote[].Transaction.IncomeFees.IncomeFee[*].IncomeData.Description',
            'Amount__c' => 'Opportunity.Quotes.Quote[].Transaction.IncomeFees.IncomeFee[*].IncomeData.Amount',
            'Percent__c' => 'Opportunity.Quotes.Quote[].Transaction.IncomeFees.IncomeFee[*].IncomeData.PercentOfTotalCost',
            'Paid_Date__c' => 'Opportunity.Quotes.Quote[].Transaction.IncomeFees.IncomeFee[*].IncomeData.FeeDate'
        };

        for (String fieldName : incomeFeeMappings.keySet()){
            String objName = 'SuperTRUMP_Quote_Income_Fee__c';
            String parentObjName = 'SuperTRUMP_Quote__c';
            String calcField = incomeFeeMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Object_Name__c = objName,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Parent_Name__c = parentObjName,
                    IST__SF_Master_Object_Name__c = parentObjName,
                    IST__SF_Object_Level__c = '2',
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }

        Map<String, String> expenseFeeMappings = new Map<String, String>{
            'Description__c' => 'Opportunity.Quotes.Quote[].Transaction.ExpenseFees.ExpenseFee[*].ExpenseData.Description',
            'Amount__c' => 'Opportunity.Quotes.Quote[].Transaction.ExpenseFees.ExpenseFee[*].ExpenseData.Amount',
            'Percent__c' => 'Opportunity.Quotes.Quote[].Transaction.ExpenseFees.ExpenseFee[*].ExpenseData.PercentOfTotalCost',
            'Paid_Date__c' => 'Opportunity.Quotes.Quote[].Transaction.ExpenseFees.ExpenseFee[*].ExpenseData.FeeDate'
        };

        for (String fieldName : expenseFeeMappings.keySet()){
            String objName = 'SuperTRUMP_Quote_Expense_Fee__c';
            String parentObjName = 'SuperTRUMP_Quote__c';
            String calcField = expenseFeeMappings.get(fieldName);
            toInsert.add(
                new IST__SuperTRUMP_Mapping__c(
                    IST__Allow_Salesforce_Changes__c = false,
                    IST__External_Binding__c = null,
                    IST__IsSynch__c = true,
                    IST__IsSynch_In__c = false,
                    IST__SF_Object_Name__c = objName,
                    IST__SF_Field_Name__c = fieldName,
                    IST__SF_Parent_Name__c = parentObjName,
                    IST__SF_Master_Object_Name__c = parentObjName,
                    IST__SF_Object_Level__c = '2',
                    IST__SOR__c = 'ST',
                    IST__ST_Field_Name__c = calcField,
                    IST__ST_Update_Priority__c = 0
                )
            );
        }
        
        List<IST__SuperTRUMP_Mapping__c> storedMappings = [SELECT
                IST__SF_Object_Name__c,
                IST__SF_Field_Name__c,
                IST__ST_Field_Name__c
            FROM IST__SuperTRUMP_Mapping__c
            WHERE IST__SF_Master_Object_Name__c = 'SuperTRUMP_Quote__c'
            LIMIT 10000];
        
        Integer idx = 0;
        while (idx < toInsert.size()){
            IST__SuperTRUMP_Mapping__c mapping = toInsert[idx];
            Boolean isFound = false;
            for (Integer sIdx = 0; sIdx < storedMappings.size(); ++sIdx){
                IST__SuperTRUMP_Mapping__c m = storedMappings[sIdx];
                if (m.IST__SF_Object_Name__c == mapping.IST__SF_Object_Name__c
                    && m.IST__SF_Field_Name__c == mapping.IST__SF_Field_Name__c
                ){
                    toInsert.remove(idx);
                    storedMappings.remove(sIdx);
                    isFound = true;
                    break;
                }
            }
            if (!isFound){
                System.debug('Mapping for ' + mapping.IST__SF_Object_Name__c + '.' + mapping.IST__SF_Field_Name__c + ' was NOT found.');
                ++idx;
            }
        }
        if (toInsert.size() > 0){
            System.debug(toInsert.size() + ' new mappings being created.');
            if (!Schema.sObjectType.IST__SuperTRUMP_Mapping__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SF_Object_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SF_Field_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SF_Parent_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__ST_Field_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SF_Object_Level__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__IsSynch__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__IsSynch_In__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SOR__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__SF_Master_Object_Name__c.isCreateable()
                || !Schema.sObjectType.IST__SuperTRUMP_Mapping__c.fields.IST__Allow_Salesforce_Changes__c.isCreateable())
            {
                throw new MappingException('You do not have permission to create an object of type IST__SuperTRUMP_Mapping__c.');
            }
            Database.insert(toInsert, true);
        }
    }
    
    public class MappingException extends Exception {}
}